### ISSUE TITLE
Unable to train after dataset migration

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [waczjoan/gaussian-mesh-splatting#21]
Hi, 

The training dataset required for this project has been moved to a new location. It can now be found [hare](https://drive.google.com/drive/folders/1cwB8jfmxMetNITRrve8hZE5ZleQLqKsW). However, I was unable to train the model with this dataset. Here is the error message that I got.

```
$ train.py --eval -s /data/ns_hotdog -m output/hotdog_flat --gs_type gs_flat -w
torch cuda:  True
Optimizing output/hotdog_flat
Output folder: output/hotdog_flat [22/10 13:05:55]
Tensorboard not available: not logging progress [22/10 13:05:55]
Traceback (most recent call last):
  File "train.py", line 267, in <module>
    args.start_checkpoint, args.debug_from, args.save_xyz
  File "train.py", line 45, in training
    scene = Scene(dataset, gaussians)
  File "/home/nisarg/projects/gaussian-mesh-splatting/scene/__init__.py", line 63, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

```
How do I fix this issue?

**Comment by waczjoan** [comment]
Hi, it looks like you don't have information about `transforms_train.json` in the directory you provide. Please check if you are specifying the right path, try specifying an absolute path. Please try debug this line: 

https://github.com/waczjoan/gaussian-mesh-splatting/blob/2b457f77a4459751f17274e5fcb1d23c1a9b5280/scene/__init__.py#L43

please check if `args.source_path` is correct source.
